name: Build and publish wheels

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
          - os: linux
            arch: aarch64
            runner: ubuntu-latest
          - os: macos
            arch: x86_64
            runner: macos-13
          - os: macos
            arch: arm64
            runner: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_PLATFORM: ${{ matrix.os }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BEFORE_ALL_LINUX: "yum install -y pkg-config openssl-devel"
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-musllinux* *-win*"
          CIBW_ENVIRONMENT: "PYO3_CONFIGURE=1"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-wheels]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          packages-dir: dist
